server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/addressdb
        username: root
        password: root@123
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
      
# Test Details for QA Environment
test:
  details: Address details for QA environment from GitHub
  employee: John Joseph
  city: Metropolis
  state: DC      
