server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/addressdb
        username: root
        password: root@123
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
      
# Test Details for QA Environment
test:
  details: Department service details for QA environment
  engineer: Jane Smith
  department: QA Testing [Dept service]
  engineerContact:
    email: qaenigneer.qa@example.com
    phone: 111-773-7890       
