server:
    port: 8082
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/employeedb
        username: root
        password: root@123
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                
# Test Details for Development Environment
test:
  details: Employee service details for development environment [From GitHub]
  employee: Mebin mathew
  email: mm@test.com   
  age: 29
