server:
    port: 8082
spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/employeesdatabase?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                
# Test Details for QA Environment
test:
  details: Employee details for QA environment from GitHub
  employee: John Joseph
  email: jj@test.com   
  age: 28              
