server:
    port: 8082
spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/employeesdatabase?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                
# Test Details for Production Environment
test:
  details: Employee details for prod environment from GitHub
  employee: Katie Ellen
  email: ke@test.com   
  age: 21
